### ISSUE TITLE
Indention for array is wrong

### ISSUE THREAD

**Issue by dkellenb** [dallgoot/yaml#20]
Tested with version 0.9.1.2

Given:
```php
$object = new \Dallgoot\Yaml\Types\YamlObject(0);
$object->api = '1';
$object->entries = array('a' => array(array('b1' => 'b', 'b2' => 'b'), array('c1' => 'c', 'c2' => 'c')));
echo \Dallgoot\Yaml\Yaml::dump($object, 0);
```

Expected:
```yaml
api: 1
entries: 
  a: 
    - b1: b
      b2: b
    - c1: c
      c2: c
```

Actual:
```
api: 1
entries: 
  a: 
    - 
  b1: b
  b2: b
    - 
  c1: c
  c2: c
```
